# Generated by Django 5.1.2 on 2024-10-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='historique_medical',
        ),
        migrations.AddField(
            model_name='patient',
            name='bodyTemperature',
            field=models.FloatField(default=37.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalHistoryLink',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.IntegerField(choices=[(0, 'Homme'), (1, 'Femme')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
